apiVersion: v1
kind: Service
metadata:
  name: interesting-service
spec:
  selector:
    app: interesting-app
  ports:
    - protocol: TCP
      port: 80       # Service port (what you access externally)
      targetPort: 5000  # Container port (where Flask runs)
  type: LoadBalancer